title: Guido Freire
url: "https://freireguido.com"
baseurl: "/"

markdown: kramdown
remote_theme: ankitsultana/researcher@gem
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Website forked from this repo"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "about"
   link: "/"
 - name: "research"
   link: "/research"
 - name: "blog"
   link: "https://freireguido.substack.com"
 - name: "cv"
   link: "/cv.pdf"
